<!DOCTYPE html>
<html lang="en">

<head>
    <title>Promise相关</title>
</head>
<style>
</style>

<body>
    <div id="app">
        分析一下promise的规范
        promise有三种状态：pending，fulfilled，rejected。
        pending代表等待的状态，在此状态下，
        可能执行resolve（）的方法，
        也可能执行reject（）方法，
        fulfilld代表成功态，此状态下执行resolve（）方法，
        rejected代表失败态，此状态下执行reject（）方法，
        一旦成功了就不能失败，反过来也是一样
        每个promsie都有一个then方法
        如果new promise 报错了会走失败态（throw new Error（'报错'）也会走失败态）
        
/**
* 1. 是个构造函数
* 2. 传入一个可执行函数 函数的入参第一个为 fullFill函数 第二个为 reject函数；  函数立即执行，  参数函数异步执行
* 3. 状态一旦更改就不可以变更  只能 pending => fulfilled 或者  pending => rejected
* 4. then 的时候要处理入参的情况 successCallback 和failCallback 均可能为非函数
*      默认的 failCallback 一定要将异常抛出， 这样下一个promise便可将其捕获 异常冒泡的目的
* 5. then 中执行回调的时候要捕获异常 将其传给下一个promise
*    如果promise状态未变更 则将回调方法添加到对应队列中
*    如果promise状态已经变更 需要异步处理成功或者失败回调
*    因为可能出现 回调结果和当前then返回的Promise一致 从而导致死循环问题
* 6. catch只是then的一种特殊的写法 方便理解和使用
* 7. finally 特点 1. 不管执行resolve或者reject都会执行
*                2. 回调没有参数
*                3. 返回一个Promise 且值可以穿透到下一个then或者catch
* 8. Promise.resolve, Promise.reject 根据其参数返回对应的值 或者状态的Promise即可
* 9. Proise.all 特点  1. 返回一个Promise
*                    2. 入参是数组 resolve的情况下出参也是数组 且结果顺序和调用顺序一致
*                    3. 所有的值或者promise都完成才能resolve 所有要计数
*                    4. 只要有一个为reject 返回的Promise便reject
* 10. Proise.race 特点 1. 返回一个Promise
*                    2. 入参是数组 那么出参根据第一个成功或者失败的参数来确定
*                    3. 只要有一个resolve 或者reject 便更改返回Promise的状态
*
*
*/
    </div>
    <script>
        const isFunction = (value) => typeof value === 'function'
        const PENDING = 'pending'
        const RESOLVED = 'fulFilled'
        const REJECTED = 'rejected'
        const resolvePromise = (promise2, x, resolve, reject) => {
            // x和promise2不能是同一个人，如果是同一个人就报错
            // 加一个开关，防止多次调用失败和成功，跟pending状态值一样的逻辑一样,走了失败就不能走成功了，走了成功一定不能在走失败
            if (promise2 === x) {
                return reject(
                    new TypeError('Chaining cycle detected for promise #<promise>')
                )
            }
            // 判断如果x是否是一个对象，判断函数是否是对象的方法有：typeof instanceof constructor toString
            if ((typeof x === 'object' && x != null) || typeof x === 'function') {
                let called
                try { // 预防取.then的时候错误
                    let then = x.then // Object.definePropertype
                    if (typeof then === 'function') {
                        // 用then.call()为了避免在使用一次x.then报错
                        then.call(x, y => {
                            // resolve(y)// 采用promise的成功结果，并且向下传递
                            if (called) {
                                return
                            }
                            called = true
                            // y有可能是一个promise，那么我们就要继续使用回调函数,直到解析出来的值是一个普通值
                            resolvePromise(promise2, y, resolve, reject)
                        }, r => {
                            if (called) {
                                return
                            }
                            called = true
                            reject(r) // 采用promise的失败结果，并且向下传递
                        })
                    } else {
                        if (called) {
                            return
                        }
                        called = true
                        resolve(x) // x不是一个函数，是一个对象
                    }
                } catch (err) {
                    if (called) {
                        return
                    }
                    called = true
                    reject(err)
                }
            } else {
                // x是一个普通值
                resolve(x)
            }
        }
        class MyPromise {
            constructor(executor) {
                this.status = PENDING
                this.value = undefined
                this.reason = undefined
                this.onResolvedCallbacks = []
                this.onRejectedCallbacks = []
                // 成功
                let resolve = (value) => {
                    // pending最屏蔽的，resolve和reject只能调用一个，不能同时调用，这就是pending的作用
                    if (this.status == PENDING) {
                        this.status = RESOLVED
                        this.value = value
                        // 发布执行函数
                        this.onResolvedCallbacks.forEach(fn => fn())
                    }
                }
                // 失败
                let reject = (reason) => {
                    if (this.status == PENDING) {
                        this.status = REJECTED
                        this.reason = reason
                        this.onRejectedCallbacks.forEach(fn => fn())
                    }
                }
                try {
                    // 执行函数
                    executor(resolve, reject)
                } catch (err) {
                    // 失败则直接执行reject函数
                    reject(err)
                }
            }
            then(onFulFilled, onRejected) {
                // onfulfilled, onrejected 都是可选参数
                onFulFilled = isFunction(onFulFilled) ? onFulFilled : data => data
                onRejected = isFunction(onRejected) ? onRejected : err => {
                    throw err
                }
                let promise2 = new MyPromise((resolve, reject) => {
                    // 箭头函数，无论this一直是指向最外层的对象
                    // 同步
                    if (this.status == RESOLVED) {
                        setTimeout(() => {
                            try {
                                let x = onFulFilled(this.value)
                                // 添加一个resolvePromise（）的方法来判断x跟promise2的状态，决定promise2是走成功还是失败
                                resolvePromise(promise2, x, resolve, reject)
                            } catch (err) { // 中间任何一个环节报错都要走reject()
                                reject(err)
                            }
                        }, 0) // 同步无法使用promise2，所以借用setiTimeout异步的方式
                        // MDN 0>=4ms
                    }
                    if (this.status == REJECTED) {
                        setTimeout(() => {
                            try {
                                let x = onRejected(this.reason)
                                resolvePromise(promise2, x, resolve, reject)
                            } catch (err) { // 中间任何一个环节报错都要走reject()
                                reject(err)
                            }
                        }, 0) // 同步无法使用promise2，所以借用setiTimeout异步的方式
                    }
                    // 异步
                    if (this.status == PENDING) {
                        // 在pending状态的时候先订阅
                        this.onResolvedCallbacks.push(() => {
                            // todo
                            setTimeout(() => {
                                try {
                                    let x = onFulFilled(this.value)
                                    resolvePromise(promise2, x, resolve, reject)
                                } catch (err) { // 中间任何一个环节报错都要走reject()
                                    reject(err)
                                }
                            }, 0) // 同步无法使用promise2，所以借用setiTimeout异步的方式
                        })
                        this.onRejectedCallbacks.push(() => {
                            // todo
                            setTimeout(() => {
                                try {
                                    let x = onRejected(this.reason)
                                    resolvePromise(promise2, x, resolve, reject)
                                } catch (err) { // 中间任何一个环节报错都要走reject()
                                    reject(err)
                                }
                            }, 0) // 同步无法使用promise2，所以借用setiTimeout异步的方式
                        })
                    }
                })
                return promise2
            }
        }
    </script>

</body>

</html>